name: Experimental Environment Setup

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-riscv64-unknown-elf \
            qemu-system-misc \
            gdb-multiarch \
            make \
            cmake \
            python3-pip \
            elfutils

      - name: Print Tool Versions
        run: |
          echo "=== GCC RISC-V ==="
          riscv64-unknown-elf-gcc --version
          echo "=== QEMU ==="
          qemu-system-riscv64 --version
          echo "=== GDB multiarch ==="
          gdb-multiarch --version

      - name: Clone user repo
        run: |
          git clone https://github.com/yuk1i/SUSTechOS
          cd SUSTechOS
          git clone https://github.com/yuk1i/SUSTechOS-2025S-user user

      - name: Build user programs
        working-directory: SUSTechOS
        run: make user

      - name: Build kernel
        working-directory: SUSTechOS
        run: make

      - name: Run QEMU (1min)
        working-directory: SUSTechOS
        run: timeout 60 make run || true
